apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dbrule
  namespace: database
spec:
  podSelector:
    matchLabels:
      tier: backend
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            tier: frontend
        podSelector:
          matchLabels:
            tier: frontend1
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            tier: frontend
        podSelector:
          matchLabels:
            tier: frontend1
