apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webrule
  namespace: wordpress
spec:
  podSelector:
    matchLabels:
      app: web
  ingress:
      from:
          podSelector: []
        - ports:
          - protocol: TCP
            port: 8080
          - protocol: TCP
            port: 8443
          - protocol: TCP
            port: 80
          - protocol: TCP
            port: 443

      

