apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webrule
  namespace: wordpress
spec:
  podSelector:
    matchLabels:
      app: web
  ingress:
    - ports:
      - port: 8080
      - port: 8443
      from: []
      
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: mariadb
        ports:
        - protocol: TCP
          port: 3306
