apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webrule
  namespace: wordpress
spec:
  podSelector:
    matchLabels:
      app: web
  ingress:
  - {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          namespace: kube-system
    ports:
    - protocol: UDP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          app: mariadb


